<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 * Implements hook_theme().
 */
function entity_reference_autores_theme() {
  return array(
    'entity_reference_autores_formatter' => array(
      'variables' => array('url'=> NULL, 'category'=> NULL, 'original_name'=> NULL, 'override_name'=> NULL),
      'template' => 'entity-reference-autores-formatter',
    ),
  );
}


